// GraphQL-compatible types (no Convex dependency)
export interface TeamMember {
  id: string;
  _id?: string; // Compatibility alias
  name: string;
  email: string;
  studentId?: string;
  major?: string;
}

export interface EnrichedTeam {
  id: string;
  _id?: string; // Compatibility alias
  name?: string;
  programId: string;
  leaderId: string;
  memberIds?: string[]; // Legacy - use members array instead
  leader?: TeamMember | null;
  members?: (TeamMember | null)[];
  supervisorId?: string;
  supervisor?: TeamMember | null;
  progress?: number;
  autoGenerated?: boolean;
  generationRunId?: string;
  generatedAt?: string;
}

export interface TeamForm {
  name: string;
  leaderId: string;
  memberIds: string[];
  supervisorId?: string;
}

// ===== Auto-generation preview types =====

export interface ProgramComposition {
  major: string;
  count: number;
}

export interface PreviewTeamMember {
  id: string;
  name: string;
  email: string;
  major: string;
}

export interface PreviewTeam {
  tempId: string;
  name: string;
  memberCount: number;
  members: PreviewTeamMember[];
  programComposition: ProgramComposition[];
}

export interface GeneratedTeamPreview {
  runId: string;
  teams: PreviewTeam[];
  unassignedStudents: PreviewTeamMember[];
}

